
create table  DW.COMPETION_DIM
(
  id INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY ,
  Competition_Id INT NOT NULL ,
  Competition_Title INT NOT NULL ,
  Team_Id INT NOT NULL ,
  EnabledDate date,
  Deadline date,
  OnlyAllowKernelSubmission NUMBER(1) default (0) NOT NULL,
  unique(Competition_Id,Team_Id),
  check (OnlyAllowKernelSubmission = 0 or OnlyAllowKernelSubmission = 1)
);

create table  DW.DATASET_DIM
(
  id INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY ,
  CreatorUserId int ,
  OwnerUserId int ,
  CurrentDatasetVersionId int, 
  Title varchar(200),
  Subtitle varchar(2000)
);

create table DW.USER_DIM
(
  id INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY ,
  userId INT NOT NULL,
  teamId INT NOT NULL,
  UserName	NVARCHAR2 (50) ,
  DisplayName	VARCHAR2 (50) ,
  RegisterDate	DATE default sysdate NOT NULL,
  PerformanceTier	NUMBER (2)	,
  unique(userId,teamId)
);

create TABLE DW.FORUM_DIM
(
   id INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY ,
   ForumID    INT NOT NULL,
   Title varchar(50) ,
   TopicId INT NOT NULL,
   CreationDate DATE default sysdate NOT NULL,
   unique(ForumID,TopicId)
);

create table DW.KERNELS_DIM
(
  id INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY ,
  AuthorUserId INT NOT NULL,
  CurrentKernelVersionId INT NOT NULL,
  CreationDate DATE default sysdate NOT NULL,
  MadePublicDate DATE default sysdate NOT NULL,	
  TotalViews INT 
);
