
INSERT INTO DW.COMPETION_DIM (
    COMPETITION_ID,
    COMPETITION_TITLE,
    TEAM_ID,
    ENABLEDDATE,
    DEADLINE,
    ONLYALLOWKERNELSUBMISSION
) 
(
  select 
      C.CompetitionId  ,
      C.Title   ,
      T.TEAMID   ,
      C.EnabledDate  ,
      C.Deadline   ,
      C.OnlyAllowKernelSubmission  
  from OP.TEAMS T
  LEFT JOIN OP.COMPETITION C
  ON T.COMPETITIONID = C.COMPETITIONID
);



INSERT INTO DW.DATASET_DIM (
    ID,
    CREATORUSERID,
    OWNERUSERID,
    CURRENTDATASETVERSIONID,
    TITLE,
    SUBTITLE
)  (
  SELECT
      DATASETID,
      CREATORUSERID,
      OWNERUSERID,
      CURRENTDATASETVERSIONID,
      TITLE,
      SUBTITLE
  FROM
      OP.DATASETS_TB  
  WHERE OWNERUSERID is not null
);


INSERT INTO DW.FORUM_DIM (
    FORUMID,
    TITLE,
    TOPICID,
    CREATIONDATE
) VALUES (
    SELECT 
  		F.FORUMID,
  		F.TITLE,
  		T.FORUMTID,
  		T.CREATIONDATE
  	FROM KAGGLE_META.FORUMTOPICS_TB T
  	LEFT JOIN KAGGLE_META.FORUM_TB F
	ON T.FORUMID=F.FORUMID
);

