CREATE OR REPLACE VIEW KAGGLE_META.VW_TAGS AS
SELECT
    TAGNAME,
    TAGID,
    SUPERTAGID,
    DESCRIPTION,
	(
      	select count(*) from KAGGLE_META.DATASETTAGS
		where KAGGLE_META.DATASETTAGS.TAGID = KAGGLE_META.TAGS_TB.TAGID 
	) as DatasetCount
	,
	(
      	select count(*) from KAGGLE_META.COMPETITIONTAGS
		where KAGGLE_META.COMPETITIONTAGS.TAGID = KAGGLE_META.TAGS_TB.TAGID 
	) as CompetitionCount
	,
	(
      	select count(*) from KAGGLE_META.KERNEL_TAGS
		where KAGGLE_META.KERNEL_TAGS.TAGID = KAGGLE_META.TAGS_TB.TAGID 
	) as KernelCount

FROM
    KAGGLE_META.TAGS_TB;




----created to support next view (competitions)
CREATE OR REPLACE VIEW KAGGLE_META.VW_TEAMS AS
SELECT
    TEAMID,
    COMPETITIONID,

	(
      select count(*) from KAGGLE_META.TEAM_MEMBERSHIPS
	   where KAGGLE_META.TEAM_MEMBERSHIPS.TEAMID=KAGGLE_META.TEAMS.TEAMID
	) as MemberCount,

	(
      select count(*) from KAGGLE_META.SUBMISSIONS
	   where KAGGLE_META.SUBMISSIONS.TEAMID=KAGGLE_META.SUBMISSIONS.TEAMID
	) as submissionCount,

    TEAMLEADERID,
    TEAMNAME,
    SCOREFIRSTSUBMITTEDDATE,
    PUBLICLEADERBOARDSUBMISSIONID,
    PRIVATELEADERBOARDSUBMISSIONID,
    ISBENCHMARK,
    MEDAL,
    MEDALAWARDDATE,
    PUBLICLEADERBOARDRANK,
    PRIVATELEADERBOARDRANK
FROM
    KAGGLE_META.TEAMS;




CREATE OR REPLACE VIEW KAGGLE_META.VW_COMPETITION AS
SELECT
    COMPETITIONID,
    TITLE,
    COMPETITIONTYPEID,
    SUBTITLE,
    FORUMID,
    ORGANIZATIONID,
    HOSTNAME,
    ENABLEDDATE,
    DEADLINE, 

	(
      	SELECT COUNT(*) FROM KAGGLE_META.TEAMS WHERE
      	KAGGLE_META.TEAMS.COMPETITIONID = KAGGLE_META.COMPETITION.COMPETITIONID
	) AS TotalTeams,
	
	(
      	SELECT SUM(MemberCount) FROM KAGGLE_META.VW_TEAMS WHERE 
      	KAGGLE_META.VW_TEAMS.COMPETITIONID = KAGGLE_META.COMPETITION.COMPETITIONID
	) AS TotalCompetitors,
	
	(
      	SELECT SUM(submissionCount) FROM KAGGLE_META.VW_TEAMS WHERE 
      	KAGGLE_META.VW_TEAMS.COMPETITIONID = KAGGLE_META.COMPETITION.COMPETITIONID
	) AS TotalSubmission,
	
	ONLYALLOWKERNELSUBMISSION
FROM
    KAGGLE_META.COMPETITION;
