--BATCH 1
CREATE OR REPLACE VIEW KAGGLE_META.VW_TAGS AS
SELECT
    TAGNAME,
    TAGID,
    SUPERTAGID,
    DESCRIPTION,
	(
      	select count(*) from KAGGLE_META.DATASETTAGS
		where KAGGLE_META.DATASETTAGS.TAGID = KAGGLE_META.TAGS_TB.TAGID 
	) as DatasetCount
	,
	(
      	select count(*) from KAGGLE_META.COMPETITIONTAGS
		where KAGGLE_META.COMPETITIONTAGS.TAGID = KAGGLE_META.TAGS_TB.TAGID 
	) as CompetitionCount
	,
	(
      	select count(*) from KAGGLE_META.KERNEL_TAGS
		where KAGGLE_META.KERNEL_TAGS.TAGID = KAGGLE_META.TAGS_TB.TAGID 
	) as KernelCount

FROM
    KAGGLE_META.TAGS_TB;




CREATE OR REPLACE VIEW KAGGLE_META.VW_TEAMS AS
SELECT
    TEAMID,
    COMPETITIONID,
	
	(
      select max(SUBMISSIONDATE) from KAGGLE_META.SUBMISSIONS
	   where KAGGLE_META.SUBMISSIONS.TEAMID=KAGGLE_META.SUBMISSIONS.TEAMID
	) as LastSubmissionDate,

	(
      select count(*) from KAGGLE_META.TEAM_MEMBERSHIPS
	   where KAGGLE_META.TEAM_MEMBERSHIPS.TEAMID=KAGGLE_META.TEAMS.TEAMID
	) as MemberCount,

	(
      select count(*) from KAGGLE_META.SUBMISSIONS
	   where KAGGLE_META.SUBMISSIONS.TEAMID=KAGGLE_META.SUBMISSIONS.TEAMID
	) as submissionCount,

    TEAMLEADERID,
    TEAMNAME,
    SCOREFIRSTSUBMITTEDDATE,
    PUBLICLEADERBOARDSUBMISSIONID,
    PRIVATELEADERBOARDSUBMISSIONID,
    ISBENCHMARK,
    MEDAL,
    MEDALAWARDDATE,
    PUBLICLEADERBOARDRANK,
    PRIVATELEADERBOARDRANK
FROM
    KAGGLE_META.TEAMS;




--BATCH 2
CREATE OR REPLACE VIEW KAGGLE_META.VW_COMPETITION AS
SELECT
    COMPETITIONID,
    TITLE,
    COMPETITIONTYPEID,
    SUBTITLE,
    FORUMID,
    ORGANIZATIONID,
    HOSTNAME,
    ENABLEDDATE,
    DEADLINE, 

	(
      	SELECT COUNT(*) FROM KAGGLE_META.TEAMS WHERE
      	KAGGLE_META.TEAMS.COMPETITIONID = KAGGLE_META.COMPETITION.COMPETITIONID
	) AS TotalTeams,
	
	(
      	SELECT SUM(MemberCount) FROM KAGGLE_META.VW_TEAMS WHERE 
      	KAGGLE_META.VW_TEAMS.COMPETITIONID = KAGGLE_META.COMPETITION.COMPETITIONID
	) AS TotalCompetitors,
	
	(
      	SELECT SUM(submissionCount) FROM KAGGLE_META.VW_TEAMS WHERE 
      	KAGGLE_META.VW_TEAMS.COMPETITIONID = KAGGLE_META.COMPETITION.COMPETITIONID
	) AS TotalSubmission,
	
	ONLYALLOWKERNELSUBMISSION
FROM
    KAGGLE_META.COMPETITION;



CREATE OR REPLACE VIEW KAGGLE_META.VW_KERNEL_VERSIONS AS
SELECT
    KVID,
    SCRIPTID,
    PARENTKVID,
    LANGUAGEID,
    AUTHORID,
    CREATIONDATE,
    VERSIONNUMBER,
    TITLE,
    EVALUATIONDATE,
    ISCHANGE,

	(
      SELECT COUNT(*) FROM KAGGLE_META.KERNEL_VOTES WHERE 
      	KAGGLE_META.KERNEL_VOTES.KVID = KAGGLE_META.KERNEL_VERSIONS.KVID
	) AS TotalVotes, 

	
    TOTALLINES,
    LINESINSERTEDFROMPREVIOUS,
    LINESCHANGEDFROMPREVIOUS,
    LINESUNCHANGEDFROMPREVIOUS,
    LINESINSERTEDFROMFORK,
    LINESDELETEDFROMFORK,
    LINESCHANGEDFROMFORK,
    LINESUNCHANGEDFROMFORK
FROM
    KAGGLE_META.KERNEL_VERSIONS;




--BATCH 3
CREATE OR REPLACE VIEW KAGGLE_META.VW_KERNELS AS
SELECT
    SCRIPTID,
    AUTHORID,
    CURRENTKERNELVERSIONID,
    FORKPARENTKERNELVERSIONID,
    FORUMTOPICID,
    FIRSTKERNELVERSIONID,
    CREATIONDATE,
    EVALUATIONDATE,
    MADEPUBLICDATE,
    ISPROJECTLANGUAGETEMPLATE,
    CURRENTURLSLUG,
    MEDAL,
	TotalViews	INT 	,


	(
      	select count(*) from KAGGLE_META.FORUMMESSAGES_TB
		where KAGGLE_META.FORUMMESSAGES_TB.FORUMTID=KAGGLE_META.KERNELS.FORUMTOPICID
	) as TotalComments,
	
	(
      SELECT SUM(TotalVotes) FROM KAGGLE_META.VW_KERNEL_VERSIONS WHERE 
      	KAGGLE_META.VW_KERNEL_VERSIONS.SCRIPTID = KAGGLE_META.KERNELS.SCRIPTID
	) AS TotalVotes, 

    MEDALAWARDDATE
FROM
    KAGGLE_META.KERNELS;
