CREATE TABLE DW.COMPETITION(
    ID INT	NOT NULL,
    CompetitionId not null,
    Title VARCHAR(255),
    TeamID INT NOT NULL,
    EnabledDate DATE,
    DeadlineDate DATE,
    OnlyAllowKernelSubmissions NUMBER(1) default (0) NOT NULL,
    TeamLeader INT NOT NULL ,
    
    UNIQUE(TeamID,CompetitionId)
);

CREATE TABLE DW.DATASET(
    ID INT NOT NULL,
    Title VARCHAR(200),
    Subtitle VARCHAR(2000),
    OwnerUserId INT,
    CurrentDatasetVersionId int 
)

CREATE TABLE DW.USERS(
    ID INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    UserId INT NOT NULL, 
    UserName VARCHAR2 (50),
    DisplayName	VARCHAR2 (50),
    RegisterDate DATE default sysdate NOT NULL,
    PerformanceTier	NUMBER (2) 
);

CREATE TABLE DW.FORUM(
    ID INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    FORUMID INT NOT NULL,
    Title varchar(50),
    Creationdate DATE,
    TopicID INT NOT NULL ,
    
    UNIQUE(FORUMID,TopicID)
);

CREATE TABLE DW.KERNEL(
    ID INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    CreationDate DATE,
    AuthorUserID INT NOT NULL,
    CurrentKernelVersionID INT,
    MadePublicDate DATE 
);

create table  DW.PERFORMANCE_FACT
(
  id INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY ,
  userId INT NOT NULL references DW.USERS(id),
  competitionsId INT NOT NULL references DW.COMPETITION(id),
  kernelId INT NOT NULL references DW.KERNEL(id),
  forumsId INT references DW.FORUM(id),
  datasetId INT references DW.DATASET(id),
  totalSubmissions INT,
  totalMedals INT,
  totalForumMessages INT,
  unique(userId,competitionsId,forumsId,kernelId,datasetId)
);
