CREATE TABLE COMPETITION{
    ID INT	NOT NULL,
    Title VARCHAR(255),
    TeamID INT NOT NULL,
    EnabledDate DATE,
    DeadlineDate DATE,
    OnlyAllowKernelSubmissions NUMBER(1) default (0) NOT NULL,
    isTeamLeader NUMBER(1) default (0) NOT NULL,

    CONSTRAINT COMPETITION_PK PRIMARY KEY (ID),
} 

CREATE TABLE DATASET{
    ID INT NOT NULL,
    Title varchar(200),
    Subtitle varchar(2000),
    CurrentDatasetVersionId int,

    CONSTRAINT DATASET_PK PRIMARY KEY (ID)
}

CREATE TABLE USER{
    ID INT NOT NULL,
    UserName VARCHAR2 (50),
    DisplayName	VARCHAR2 (50),
    RegisterDate DATE default sysdate NOT NULL,
    PerformanceTier	NUMBER (2),

    CONSTRAINT USER_PK PRIMARY KEY (ID)
}

CREATE TABLE FORUM{
    ID INT NOT NULL,
    Title varchar(50),
    Creationdate DATE,
    TopicID INT NOT NULL,

    CONSTRAINT FORUMS_PK PRIMARY KEY (ID)
}

CREATE TABLE KERNEL{
    ID INT NOT NULL,
    CreationDate DATE,
    AuthorUserID INT NOT NULL,
    CurrentKernelVersionID INT,
    MadePublicDate DATE,

    CONSTRAINT KERNEL_PK PRIMARY KEY (ID)
}

CREATE TABLE PERFORMANCE_FACT{
    ID INT NOT NULL,
    UsersID INT NOT NULL,
    CompetitionsID INT NOT NULL,
    DatasetsID INT NOT NULL,
    ForumsID INT NOT NULL,
    KernelsID INT NOT NULL,
    TotalSubmissions INT,
    TotalMedals INT,
    TotalForumMessages INT,

    CONSTRAINT PERFORMANCE_FACT_PK PRIMARY KEY (ID),
    CONSTRAINT PERFORMANCE_FACT_FK1 FOREIGN KEY (UsersID) REFERENCES USER(ID),
    CONSTRAINT PERFORMANCE_FACT_FK2 FOREIGN KEY (CompetitionsID) REFERENCES COMPETITION(ID),
    CONSTRAINT PERFORMANCE_FACT_FK2 FOREIGN KEY (DatasetsID) REFERENCES DATASET(ID),
    CONSTRAINT PERFORMANCE_FACT_FK2 FOREIGN KEY (ForumsID) REFERENCES FORUM(ID),
    CONSTRAINT PERFORMANCE_FACT_FK2 FOREIGN KEY (KernelsID) REFERENCES KERNEL(ID)
}