CREATE TABLE DW.COMPETITION{
    ID INT	NOT NULL,
    Title VARCHAR(255),
    TeamID INT NOT NULL,
    EnabledDate DATE,
    DeadlineDate DATE,
    OnlyAllowKernelSubmissions NUMBER(1) default (0) NOT NULL,
    TeamLeader INT NOT NULL,

    CONSTRAINT COMPETITION_PK PRIMARY KEY (ID),
} 

CREATE TABLE DW.DATASET{
    ID INT NOT NULL,
    Title VARCHAR(200),
    Subtitle VARCHAR(2000),
    OwnerUserId INT,
    CurrentDatasetVersionId int,

    CONSTRAINT DATASET_PK PRIMARY KEY (ID)
}

CREATE TABLE DW.USER{
    ID INT NOT NULL,
    UserName VARCHAR2 (50),
    DisplayName	VARCHAR2 (50),
    RegisterDate DATE default sysdate NOT NULL,
    PerformanceTier	NUMBER (2),

    CONSTRAINT USER_PK PRIMARY KEY (ID)
}

CREATE TABLE DW.FORUM{
    ID INT NOT NULL,
    Title varchar(50),
    Creationdate DATE,
    TopicID INT NOT NULL,

    CONSTRAINT FORUMS_PK PRIMARY KEY (ID)
}

CREATE TABLE DW.KERNEL{
    ID INT NOT NULL,
    CreationDate DATE,
    AuthorUserID INT NOT NULL,
    CurrentKernelVersionID INT,
    MadePublicDate DATE,

    CONSTRAINT KERNEL_PK PRIMARY KEY (ID)
}

CREATE TABLE DW.PERFORMANCE_FACT{
    ID INT NOT NULL,
    UsersID INT NOT NULL,
    CompetitionsID INT NOT NULL,
    DatasetsID INT NOT NULL,
    ForumsID INT NOT NULL,
    KernelsID INT NOT NULL,
    TotalSubmissions INT,
    TotalMedals INT,
    TotalForumMessages INT,

    CONSTRAINT PERFORMANCE_FACT_PK PRIMARY KEY (ID),
    CONSTRAINT PERFORMANCE_FACT_FK1 FOREIGN KEY (UsersID) REFERENCES USER(ID),
    CONSTRAINT PERFORMANCE_FACT_FK2 FOREIGN KEY (CompetitionsID) REFERENCES COMPETITION(ID),
    CONSTRAINT PERFORMANCE_FACT_FK2 FOREIGN KEY (DatasetsID) REFERENCES DATASET(ID),
    CONSTRAINT PERFORMANCE_FACT_FK2 FOREIGN KEY (ForumsID) REFERENCES FORUM(ID),
    CONSTRAINT PERFORMANCE_FACT_FK2 FOREIGN KEY (KernelsID) REFERENCES KERNEL(ID)
}