INSERT INTO LANGUAGES (LANGUAGEID,LANGUAGENAME,DISPLAYNAME,ISNOTEBOOK) VALUES (1,'R','R',1);
INSERT INTO LANGUAGES (LANGUAGEID,LANGUAGENAME,DISPLAYNAME,ISNOTEBOOK) VALUES (2,'Python','Python',1);
INSERT INTO LANGUAGES (LANGUAGEID,LANGUAGENAME,DISPLAYNAME,ISNOTEBOOK) VALUES (5,'RMarkdown','R',1);
INSERT INTO LANGUAGES (LANGUAGEID,LANGUAGENAME,DISPLAYNAME,ISNOTEBOOK) VALUES (8,'IPython Notebook','Python',1);
INSERT INTO LANGUAGES (LANGUAGEID,LANGUAGENAME,DISPLAYNAME,ISNOTEBOOK) VALUES (9,'IPython Notebook HTML','Python',1);
INSERT INTO LANGUAGES (LANGUAGEID,LANGUAGENAME,DISPLAYNAME,ISNOTEBOOK) VALUES (12,'R Notebook HTML','R',1);
INSERT INTO LANGUAGES (LANGUAGEID,LANGUAGENAME,DISPLAYNAME,ISNOTEBOOK) VALUES (13,'R Notebook','R',1);
INSERT INTO LANGUAGES (LANGUAGEID,LANGUAGENAME,DISPLAYNAME,ISNOTEBOOK) VALUES (14,'Python Script - Interactive','Python',1);
INSERT INTO LANGUAGES (LANGUAGEID,LANGUAGENAME,DISPLAYNAME,ISNOTEBOOK) VALUES (15,'R Script - Interactive','R',1);
INSERT INTO LANGUAGES (LANGUAGEID,LANGUAGENAME,DISPLAYNAME,ISNOTEBOOK) VALUES (16,'RMarkdown - Interactive','R',1);

INSERT INTO USERS ( USERID, USERNAME, DISPLAYNAME, REGISTERDATE, PERFORMANCETIER ) VALUES ( 1,'kaggleteam','Kaggle Team',TO_DATE('03/24/2011','mm/dd/yyyy'),5 );
INSERT INTO USERS ( USERID, USERNAME, DISPLAYNAME, REGISTERDATE, PERFORMANCETIER ) VALUES ( 368,'antgoldbloom','Anthony Goldbloom',TO_DATE('01/20/2010','mm/dd/yyyy'),5 );
INSERT INTO USERS ( USERID, USERNAME, DISPLAYNAME, REGISTERDATE, PERFORMANCETIER ) VALUES ( 381,'iguyon','Isabelle',TO_DATE('01/29/2010','mm/dd/yyyy'),2 );
INSERT INTO USERS ( USERID, USERNAME, DISPLAYNAME, REGISTERDATE, PERFORMANCETIER ) VALUES ( 383,'davidstephan','David Stephan',TO_DATE('02/01/2010','mm/dd/yyyy'),0 );
INSERT INTO USERS ( USERID, USERNAME, DISPLAYNAME, REGISTERDATE, PERFORMANCETIER ) VALUES ( 384,'gabewarren','Gabe Warren',TO_DATE('02/02/2010','mm/dd/yyyy'),0 );
INSERT INTO USERS ( USERID, USERNAME, DISPLAYNAME, REGISTERDATE, PERFORMANCETIER ) VALUES ( 385,'demonjosh','Demon Josh',TO_DATE('02/02/2010','mm/dd/yyyy'),0 );
INSERT INTO USERS ( USERID, USERNAME, DISPLAYNAME, REGISTERDATE, PERFORMANCETIER ) VALUES ( 386,'brentshepherd','Brent Shepherd',TO_DATE('02/02/2010','mm/dd/yyyy'),0 );
INSERT INTO USERS ( USERID, USERNAME, DISPLAYNAME, REGISTERDATE, PERFORMANCETIER ) VALUES ( 387,'nicholasgruen','Nicholas Gruen',TO_DATE('02/02/2010','mm/dd/yyyy'),0 );
INSERT INTO USERS ( USERID, USERNAME, DISPLAYNAME, REGISTERDATE, PERFORMANCETIER ) VALUES ( 388,'vaibhavsrivastava0','Vaibhav Srivastava',TO_DATE('02/03/2010','mm/dd/yyyy'),0 );
INSERT INTO USERS ( USERID, USERNAME, DISPLAYNAME, REGISTERDATE, PERFORMANCETIER ) VALUES ( 389,'anandjeyahar','Anand Jeyahar',TO_DATE('02/03/2010','mm/dd/yyyy'),1 );
INSERT INTO USERS ( USERID, USERNAME, DISPLAYNAME, REGISTERDATE, PERFORMANCETIER ) VALUES ( 993,'benhamner','Ben Hamner',TO_DATE('05/31/2010','mm/dd/yyyy'),5 );
INSERT INTO USERS ( USERID, USERNAME, DISPLAYNAME, REGISTERDATE, PERFORMANCETIER ) VALUES ( 67483,'kmader','K Scott Mader',TO_DATE('11/04/2012','mm/dd/yyyy'),3 );
INSERT INTO USERS ( USERID, USERNAME, DISPLAYNAME, REGISTERDATE, PERFORMANCETIER ) VALUES ( 391404,'parulpandey','Parul Pandey',TO_DATE('07/26/2015','mm/dd/yyyy'),4 );
INSERT INTO USERS ( USERID, USERNAME, DISPLAYNAME, REGISTERDATE, PERFORMANCETIER ) VALUES ( 1302389,'imdevskp','Devakumar kp',TO_DATE('09/30/2017','mm/dd/yyyy'),3 );
INSERT INTO USERS ( USERID, USERNAME, DISPLAYNAME, REGISTERDATE, PERFORMANCETIER ) VALUES ( 1663522,'lavanyashukla01','Lavanya Shukla',TO_DATE('02/23/2018','mm/dd/yyyy'),2 );

