




--BATCH 1
CREATE OR REPLACE VIEW VW_TAGS AS
SELECT
    TAGNAME,
    TAGID,
    SUPERTAGID,
    DESCRIPTION,
	(
      	select count(*) from DATASETTAGS
		where DATASETTAGS.TAGID = TAGS_TB.TAGID 
	) as DatasetCount
	,
	(
      	select count(*) from COMPETITIONTAGS
		where COMPETITIONTAGS.TAGID = TAGS_TB.TAGID 
	) as CompetitionCount
	,
	(
      	select count(*) from KERNEL_TAGS
		where KERNEL_TAGS.TAGID = TAGS_TB.TAGID 
	) as KernelCount

FROM
    TAGS_TB;



CREATE OR REPLACE VIEW VW_SUBMISSIONS AS
SELECT
    SUBMISSIONS.SUBMISSIONID,
    SUBMISSIONS.USERID,
    SUBMISSIONS.TEAMID,
    SUBMISSIONS.SOURCEKERNELVERSIONID,
    SUBMISSIONS.SUBMISSIONDATE,
    SUBMISSIONS.SCOREDATE,
    SUBMISSIONS.PUBLICSCORELEADERBOARDDISPLAY,
    SUBMISSIONS.PUBLICSCOREFULLPRECISION,
    SUBMISSIONS.PRIVATESCORELEADERBOARDDISPLAY,
    SUBMISSIONS.PRIVATESCOREFULLPRECISION,
	
	CASE 
      WHEN COMPETITION.DEADLINE >= SUBMISSIONS.SUBMISSIONDATE
			THEN 0
           ELSE 1              
      END IsAfterDeadline

FROM
    SUBMISSIONS 
LEFT JOIN TEAMS
	ON TEAMS.TEAMID = SUBMISSIONS.TEAMID
LEFT JOIN COMPETITION
	ON COMPETITION.COMPETITIONID = TEAMS.COMPETITIONID;



CREATE OR REPLACE VIEW VW_TEAMS AS
SELECT
    TEAMID,
    COMPETITIONID,
	
	(
      select max(SUBMISSIONDATE) from SUBMISSIONS
	   where SUBMISSIONS.TEAMID=SUBMISSIONS.TEAMID
	) as LastSubmissionDate,

	(
      select count(*) from TEAM_MEMBERSHIPS
	   where TEAM_MEMBERSHIPS.TEAMID=TEAMS.TEAMID
	) as MemberCount,

	(
      select count(*) from SUBMISSIONS
	   where SUBMISSIONS.TEAMID=SUBMISSIONS.TEAMID
	) as submissionCount,

    TEAMLEADERID,
    TEAMNAME,
    SCOREFIRSTSUBMITTEDDATE,
    PUBLICLEADERBOARDSUBMISSIONID,
    PRIVATELEADERBOARDSUBMISSIONID,
    ISBENCHMARK,
    MEDAL,
    MEDALAWARDDATE,
    PUBLICLEADERBOARDRANK,
    PRIVATELEADERBOARDRANK
FROM
    TEAMS;




CREATE OR REPLACE VIEW VW_FORUMTOPICS AS
SELECT
    FORUMTID,
    FORUMID,
    CREATIONDATE,
    TOTALVIEWS,
    SCORE,
	
	(
      select MAX(FORUMMESSAGES_TB.POSTDATE) from FORUMMESSAGES_TB
		WHERE FORUMMESSAGES_TB.FORUMTID = FORUMTOPICS_TB.FORUMTID
	) as LastCommentDate,

	(
      SELECT COUNT(*) FROM FORUMMESSAGES_TB
		WHERE FORUMMESSAGES_TB.FORUMTID = FORUMTOPICS_TB.FORUMTID
	) AS TotalMessages

FROM
    FORUMTOPICS_TB;







--BATCH 2
CREATE OR REPLACE VIEW VW_COMPETITION AS
SELECT
    COMPETITIONID,
    TITLE,
    COMPETITIONTYPEID,
    SUBTITLE,
    FORUMID,
    ORGANIZATIONID,
    HOSTNAME,
    ENABLEDDATE,
    DEADLINE, 

	(
      	SELECT COUNT(*) FROM TEAMS WHERE
      	TEAMS.COMPETITIONID = COMPETITION.COMPETITIONID
	) AS TotalTeams,
	
	(
      	SELECT SUM(MemberCount) FROM VW_TEAMS WHERE 
      	VW_TEAMS.COMPETITIONID = COMPETITION.COMPETITIONID
	) AS TotalCompetitors,
	
	(
      	SELECT SUM(submissionCount) FROM VW_TEAMS WHERE 
      	VW_TEAMS.COMPETITIONID = COMPETITION.COMPETITIONID
	) AS TotalSubmission,
	
	ONLYALLOWKERNELSUBMISSION
FROM
    COMPETITION;



CREATE OR REPLACE VIEW VW_KERNEL_VERSIONS AS
SELECT
    KVID,
    SCRIPTID,
    PARENTKVID,
    LANGUAGEID,
    AUTHORID,
    CREATIONDATE,
    VERSIONNUMBER,
    TITLE,
    EVALUATIONDATE,
    ISCHANGE,

	(
      SELECT COUNT(*) FROM KERNEL_VOTES WHERE 
      	KERNEL_VOTES.KVID = KERNEL_VERSIONS.KVID
	) AS TotalVotes, 

	
    TOTALLINES,
    LINESINSERTEDFROMPREVIOUS,
    LINESCHANGEDFROMPREVIOUS,
    LINESUNCHANGEDFROMPREVIOUS,
    LINESINSERTEDFROMFORK,
    LINESDELETEDFROMFORK,
    LINESCHANGEDFROMFORK,
    LINESUNCHANGEDFROMFORK
FROM
    KERNEL_VERSIONS;



CREATE OR REPLACE VIEW VW_FORUMMESSAGES AS
SELECT
    FORUMMID,
    FORUMTID,
    USERID,
    MESSAGE,
    MEDAL,
    POSTDATE,
    REPLYTOFORUMMESSAGEID,

	(
      select count(*) from FORUMMESSAGEVOTES
		where FORUMMESSAGEVOTES.FORUMMESSAGEID = FORUMMESSAGES_TB.FORUMMID
	) AS TotalVotes

FROM
    FORUMMESSAGES_TB;



CREATE OR REPLACE VIEW VW_DATASETVERSIONS AS 
SELECT
    DATASETVID,
    DATASETID,

	(
      select count(DISTINCT KERNEL_VERSIONS.SCRIPTID) from KERNEL_VERSION_DATASETSOURCES
		LEFT JOIN KERNEL_VERSIONS ON 
		KERNEL_VERSION_DATASETSOURCES.KVID = KERNEL_VERSIONS.KVID
	) AS totalKernels,

    CREATORUSERID,
    CREATIONDATE,
    DESCRIPTION,
    VERSIONNOTES,
    TOTALCOMPRESSEDBYTES
FROM
    DATASETVERSIONS_TB;







--BATCH 3
CREATE OR REPLACE VIEW VW_KERNELS AS
SELECT
    SCRIPTID,
    AUTHORID,
    CURRENTKERNELVERSIONID,
    FORKPARENTKERNELVERSIONID,
    FORUMTOPICID,
    FIRSTKERNELVERSIONID,
    CREATIONDATE,
    EVALUATIONDATE,
    MADEPUBLICDATE,
    ISPROJECTLANGUAGETEMPLATE,
    CURRENTURLSLUG,
    MEDAL,
	TotalViews	INT 	,


	(
      	select count(*) from FORUMMESSAGES_TB
		where FORUMMESSAGES_TB.FORUMTID=KERNELS.FORUMTOPICID
	) as TotalComments,
	
	(
      SELECT SUM(TotalVotes) FROM VW_KERNEL_VERSIONS WHERE 
      	VW_KERNEL_VERSIONS.SCRIPTID = KERNELS.SCRIPTID
	) AS TotalVotes, 

    MEDALAWARDDATE
FROM
    KERNELS;
    
    
    
 

CREATE OR REPLACE VIEW VW_DATASETS AS 
SELECT
    TITLE,
    SUBTITLE,
    DATASETID,
    TAGID,
    CREATORUSERID,
    OWNERUSERID,
    OWNERORGANIZATIONID,
    CURRENTDATASETVERSIONID,
    KERNELID,

	(
      	select sum(VW_DATASETVERSIONS.totalKernels) from VW_DATASETVERSIONS where
      	VW_DATASETVERSIONS.DATASETID = DATASETS_TB.DATASETID
	)AS TotalKernels, 

    DATASOURCEID
FROM
    DATASETS_TB;
